# Generated by Django 3.2.12 on 2024-05-08 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20240415_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='follows',
        ),
        migrations.AddField(
            model_name='post',
            name='is_liked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
